### ISSUE TITLE
Boardを良い感じにJSONにする

### ISSUE THREAD

**Issue by KazuyaMiyashita** [serviver-agent/shogi-api-server#6]

**Comment by YuMuuu** [comment]
形式はjsonできまりなの？

**Comment by KazuyaMiyashita** [comment]
> 形式はjsonできまりなの？

通常のHTTPリクエストとWebSocketを利用する予定なので、両者で扱いが簡単ならなんでも良いです。

**Comment by YuMuuu** [comment]
http://shogidokoro.starfree.jp/usi.html

SFENみたいな形式にしたい。
既存のコンピュータ将棋の規格に寄せてイカした規格にしたい

**Comment by YuMuuu** [comment]
一旦jsonでの提供にして、後でSFEN風のAPIを提供するっていうのでもおｋ

**Comment by KazuyaMiyashita** [comment]
> 一旦jsonでの提供にして、後でSFEN風のAPIを提供するっていうのでもおｋ

👍 

SFEN風のプロトコルは興味があるものの、その実装で開発全体がストップするのは非効率なので、
実装したくなった時は別途issueを立てて簡単なプロトタイプの作成をお願いします。

**Comment by YuMuuu** [comment]
これやる

**Comment by KazuyaMiyashita** [comment]
このPRで実装してしまったわ

https://github.com/serviver-agent/shogi-api-server/pull/10
